version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: szczurtv
    ports:
      - "8082:8080"
    volumes:
      - ./dataprotectionkeys:/root/.aspnet/DataProtection-Keys
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
    - app-network

  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h $$POSTGRES_HOST -p $$POSTGRES_PORT"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx_rtmp:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_rtmp
    ports:
      - "1935:1935"  # RTMP port
      - "8083:8080"  # HTTP port for HLS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /tmp/hls:/tmp/hls
    networks:
      - app-network
    restart: always

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge