version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dataprotectionkeys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: myPassword
      POSTGRES_DB: myDb
      POSTGRES_USER: myUser
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: