version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./dataprotectionkeys:/root/.aspnet/DataProtection-Keys
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -h $$POSTGRES_HOST -p $$POSTGRES_PORT"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  nginx-rtmp:
    image: alfg/nginx-rtmp
    ports:
      - "1935:1935"
      - "8080:80"
    restart: always
#   use to change nginx conf
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf 



volumes:
  postgres-data: