version: '3.8'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: example
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dataprotectionkeys:/root/.aspnet/DataProtection-Keys
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ConnectionStrings__Default=Server=db;Port=5432;Database=myDatabase;User Id=postgres;Password=example;
    # depends_on:
    #   - db

# volumes:
#   postgres-data:
