# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dotnet-version: ['8.0.x', '7.0.x']

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore .NET tools
      run: dotnet tool restore

    - name: Restore NuGet packages
      run: dotnet restore
      working-directory: SzczurTv

    - name: Check formatting with CSharpier
      run: dotnet csharpier --check .
      working-directory: SzczurTv

    - name: Build
      run: dotnet build --no-restore
      working-directory: SzczurTv

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: SzczurTv

